#!/usr/bin/env python3
"""Build the RexWolf gallery from images dropped into gallery-source/."""
from __future__ import annotations

from datetime import datetime, timezone
import json
import re
import shutil
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError:
    print("Pillow is required. On Debian run: apt install python3-pil")
    raise SystemExit(1)


ROOT = Path(__file__).resolve().parent
GALLERY_HTML = ROOT / "gallery.html"
SOURCE = ROOT / "gallery-source"
THUMBS = ROOT / "assets" / "images" / "thumbs" / "gallery"
FULL = ROOT / "assets" / "images" / "full" / "gallery"
DATA = ROOT / "gallery-data.js"
INFO = ROOT / "gallery-info.json"

SUPPORTED = {
    ".jpg",
    ".jpeg",
    ".png",
    ".webp",
    ".gif",
    ".bmp",
    ".tif",
    ".tiff",
}


def slugify(value: str) -> str:
    value = value.lower().strip()
    value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    return value or "image"


def pretty_title(stem: str) -> str:
    stem = re.sub(r"^\d+[. _-]*", "", stem)
    stem = re.sub(r"[_-]+", " ", stem)
    stem = re.sub(r"\s+", " ", stem).strip()
    return stem.title() or "Untitled"


def relative_web(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def fit_and_save(
    source: Path,
    destination: Path,
    max_size: tuple[int, int],
    quality: int,
) -> tuple[int, int]:
    with Image.open(source) as opened:
        image = ImageOps.exif_transpose(opened)

        if getattr(image, "is_animated", False):
            image.seek(0)

        if image.mode not in ("RGB", "RGBA"):
            image = image.convert(
                "RGBA" if "transparency" in image.info else "RGB"
            )

        image.thumbnail(max_size, Image.Resampling.LANCZOS)
        destination.parent.mkdir(parents=True, exist_ok=True)
        image.save(destination, "WEBP", quality=quality, method=4)

        return image.size


def update_cache_version() -> str:
    version = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    html = GALLERY_HTML.read_text(encoding="utf-8")

    html = re.sub(
        r'<script src="gallery-data\.js(?:\?v=[^"]*)?"></script>',
        f'<script src="gallery-data.js?v={version}"></script>',
        html,
    )

    html = re.sub(
        r'<script src="gallery\.js(?:\?v=[^"]*)?"></script>',
        f'<script src="gallery.js?v={version}"></script>',
        html,
    )

    GALLERY_HTML.write_text(html, encoding="utf-8")
    return version


def main() -> int:
    SOURCE.mkdir(exist_ok=True)

    metadata = (
        json.loads(INFO.read_text(encoding="utf-8"))
        if INFO.exists()
        else {}
    )

    files = sorted(
        (
            path
            for path in SOURCE.rglob("*")
            if path.is_file() and path.suffix.lower() in SUPPORTED
        ),
        key=lambda path: path.relative_to(SOURCE).as_posix().lower(),
    )

    if not files:
        print(f"No supported images found in {SOURCE}")
        return 1

    shutil.rmtree(THUMBS, ignore_errors=True)
    shutil.rmtree(FULL, ignore_errors=True)

    THUMBS.mkdir(parents=True, exist_ok=True)
    FULL.mkdir(parents=True, exist_ok=True)

    used: set[str] = set()
    items: list[dict[str, object]] = []

    for number, source in enumerate(files, 1):
        rel = source.relative_to(SOURCE)
        key = rel.as_posix()
        details = metadata.get(key, metadata.get(source.name, {}))

        title = details.get("title") or pretty_title(source.stem)
        caption = details.get("caption") or ""
        category = details.get("category") or (
            rel.parent.name if rel.parent != Path(".") else "Gallery"
        )

        slug = slugify(source.stem)
        base = slug
        counter = 2

        while slug in used:
            slug = f"{base}-{counter}"
            counter += 1

        used.add(slug)

        thumb_path = THUMBS / f"{slug}.webp"
        full_path = FULL / f"{slug}.webp"

        fit_and_save(source, thumb_path, (640, 640), 82)
        full_size = fit_and_save(source, full_path, (2200, 2200), 88)

        items.append(
            {
                "title": title,
                "caption": caption,
                "category": category,
                "thumb": relative_web(thumb_path),
                "src": relative_web(full_path),
                "downloadName": source.name,
                "width": full_size[0],
                "height": full_size[1],
            }
        )

        print(
            f"[{number}/{len(files)}] "
            f"{key} -> {slug}.webp "
            f"({full_size[0]}×{full_size[1]})"
        )

    DATA.write_text(
        "// Generated by build_gallery.py. Do not edit by hand.\n"
        "window.GALLERY_IMAGES = "
        + json.dumps(items, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )

    version = update_cache_version()

    print(f"\nGallery updated: {len(items)} images")
    print(f"Cache version updated: {version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
