#!/usr/bin/env python3
"""Build the RexWolf sticker gallery from sticker-source/."""
from __future__ import annotations
from datetime import datetime, timezone
import json, re, shutil
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError:
    print("Pillow is required. On Debian run: sudo apt install python3-pil")
    raise SystemExit(1)

ROOT=Path(__file__).resolve().parent
HTML=ROOT/"stickers.html"
SOURCE=ROOT/"sticker-source"
THUMBS=ROOT/"assets/images/thumbs/stickers"
FULL=ROOT/"assets/images/full/stickers"
DATA=ROOT/"sticker-data.js"
INFO=ROOT/"sticker-info.json"
SUPPORTED={".jpg",".jpeg",".png",".webp",".gif",".bmp",".tif",".tiff"}

def slugify(value):
    value=re.sub(r"[^a-z0-9]+","-",value.lower().strip()).strip("-")
    return value or "sticker"

def pretty_title(stem):
    stem=re.sub(r"^\d+[. _-]*","",stem)
    stem=re.sub(r"[_-]+"," ",stem)
    return re.sub(r"\s+"," ",stem).strip().title() or "Untitled"

def relative_web(path):
    return path.relative_to(ROOT).as_posix()

def save_webp(source,destination,max_size,quality):
    with Image.open(source) as opened:
        image=ImageOps.exif_transpose(opened)
        if getattr(image,"is_animated",False): image.seek(0)
        if image.mode not in ("RGBA","LA"): image=image.convert("RGBA")
        image.thumbnail(max_size,Image.Resampling.LANCZOS)
        destination.parent.mkdir(parents=True,exist_ok=True)
        image.save(destination,"WEBP",quality=quality,method=4)
        return image.size

def update_cache_version():
    version=datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    html=HTML.read_text(encoding="utf-8")
    html=re.sub(r'<script src="/sticker-data\.js(?:\?v=[^"]*)?"></script>',
                f'<script src="/sticker-data.js?v={version}"></script>',html)
    html=re.sub(r'<script src="/stickers\.js(?:\?v=[^"]*)?"></script>',
                f'<script src="/stickers.js?v={version}"></script>',html)
    HTML.write_text(html,encoding="utf-8")
    return version

def main():
    SOURCE.mkdir(exist_ok=True)
    metadata=json.loads(INFO.read_text(encoding="utf-8")) if INFO.exists() else {}
    files=sorted((p for p in SOURCE.rglob("*") if p.is_file() and p.suffix.lower() in SUPPORTED),
                 key=lambda p:p.relative_to(SOURCE).as_posix().lower())
    if not files:
        print(f"No supported images found in {SOURCE}")
        return 1
    shutil.rmtree(THUMBS,ignore_errors=True); shutil.rmtree(FULL,ignore_errors=True)
    THUMBS.mkdir(parents=True,exist_ok=True); FULL.mkdir(parents=True,exist_ok=True)
    used=set(); items=[]
    for number,source in enumerate(files,1):
        rel=source.relative_to(SOURCE); key=rel.as_posix()
        details=metadata.get(key,metadata.get(source.name,{}))
        title=details.get("title") or pretty_title(source.stem)
        caption=details.get("caption") or ""
        category=details.get("category") or "Sticker"
        slug=slugify(source.stem); base=slug; counter=2
        while slug in used:
            slug=f"{base}-{counter}"; counter+=1
        used.add(slug)
        thumb=THUMBS/f"{slug}.webp"; full=FULL/f"{slug}.webp"
        save_webp(source,thumb,(384,384),88)
        size=save_webp(source,full,(1024,1024),94)
        items.append({"title":title,"caption":caption,"category":category,
                      "thumb":relative_web(thumb),"src":relative_web(full),
                      "download":relative_web(source),"downloadName":source.name,
                      "width":size[0],"height":size[1]})
        print(f"[{number}/{len(files)}] {key} -> {slug}.webp ({size[0]}×{size[1]})")
    DATA.write_text("// Generated by build_stickers.py. Do not edit by hand.\n"
                    "window.STICKER_IMAGES = "+json.dumps(items,ensure_ascii=False,indent=2)+";\n",
                    encoding="utf-8")
    version=update_cache_version()
    print(f"\nSticker gallery updated: {len(items)} images")
    print(f"Cache version updated: {version}")
    return 0

if __name__=="__main__":
    raise SystemExit(main())
