// Generated by build_gallery.py. Do not edit by hand.
window.GALLERY_IMAGES = [
  {
    "title": "Main Reference Sheet",
    "caption": "Rex’s main character reference sheet.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/000-wolf-main-refsheet.webp",
    "src": "assets/images/full/gallery/000-wolf-main-refsheet.webp",
    "downloadName": "000.Wolf_Main_Refsheet.PNG",
    "width": 2200,
    "height": 1467
  },
  {
    "title": "Original Reference Sheet",
    "caption": "An earlier Rex character reference sheet.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/001-old-wolfrefsheet.webp",
    "src": "assets/images/full/gallery/001-old-wolfrefsheet.webp",
    "downloadName": "001.old_wolfrefsheet.png",
    "width": 2200,
    "height": 1320
  },
  {
    "title": "Portrait",
    "caption": "Art by Garauwu.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/002-rex-portrait.webp",
    "src": "assets/images/full/gallery/002-rex-portrait.webp",
    "downloadName": "002.Rex_Portrait.png",
    "width": 2000,
    "height": 2000
  },
  {
    "title": "Portrait W/O Glasses",
    "caption": "Art by Garauwu.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/003-rex-portrait-noglasses.webp",
    "src": "assets/images/full/gallery/003-rex-portrait-noglasses.webp",
    "downloadName": "003.Rex_Portrait_noglasses.png",
    "width": 2000,
    "height": 2000
  },
  {
    "title": "Spotify Poster",
    "caption": "Art by Hal0.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/004-spotify-poster.webp",
    "src": "assets/images/full/gallery/004-spotify-poster.webp",
    "downloadName": "004.Spotify_Poster.jpg",
    "width": 2048,
    "height": 2048
  },
  {
    "title": "Wolf Portrait",
    "caption": "Art by Star Sprit Wolf.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/005-spritstar-portrait.webp",
    "src": "assets/images/full/gallery/005-spritstar-portrait.webp",
    "downloadName": "005.spritstar_portrait.JPG",
    "width": 1536,
    "height": 2048
  },
  {
    "title": "Gift Art",
    "caption": "Art by Chudraw.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/006-chudraw-portrait.webp",
    "src": "assets/images/full/gallery/006-chudraw-portrait.webp",
    "downloadName": "006.chudraw_portrait.png",
    "width": 1080,
    "height": 1920
  },
  {
    "title": "Wolf Doodle",
    "caption": "Art by HareThere",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/007-harethere-portrait.webp",
    "src": "assets/images/full/gallery/007-harethere-portrait.webp",
    "downloadName": "007.Harethere_portrait.png",
    "width": 1000,
    "height": 1000
  },
  {
    "title": "Ski Boi",
    "caption": "Art by ArcaneVixen.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/008-ski-boi.webp",
    "src": "assets/images/full/gallery/008-ski-boi.webp",
    "downloadName": "008.Ski-Boi.png",
    "width": 2200,
    "height": 2200
  },
  {
    "title": "Cube Break",
    "caption": "Art by Hal0.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/009-rubics-cube.webp",
    "src": "assets/images/full/gallery/009-rubics-cube.webp",
    "downloadName": "009.Rubics_cube.png",
    "width": 2048,
    "height": 2048
  },
  {
    "title": "Badge",
    "caption": "Badge by Shep.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/010-shep-badge.webp",
    "src": "assets/images/full/gallery/010-shep-badge.webp",
    "downloadName": "010.shep_badge.jpg",
    "width": 849,
    "height": 1298
  },
  {
    "title": "Woof Hat",
    "caption": "Art by Hal0",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/011-woof-hat.webp",
    "src": "assets/images/full/gallery/011-woof-hat.webp",
    "downloadName": "011.Woof_hat.jpg",
    "width": 2200,
    "height": 2200
  },
  {
    "title": "Chillin",
    "caption": "Art by Garauwu.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/012-rockandroll.webp",
    "src": "assets/images/full/gallery/012-rockandroll.webp",
    "downloadName": "012.RockandRoll.PNG",
    "width": 1325,
    "height": 2200
  },
  {
    "title": "Aditional Refrance details",
    "caption": "Art by NattyKool.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/013-aditional-referanece-art.webp",
    "src": "assets/images/full/gallery/013-aditional-referanece-art.webp",
    "downloadName": "013.aditional_Referanece_art.png",
    "width": 1941,
    "height": 2200
  },
  {
    "title": "Arcade Night",
    "caption": "Art by Garauwu.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/014-wolfs-arcade.webp",
    "src": "assets/images/full/gallery/014-wolfs-arcade.webp",
    "downloadName": "014.Wolfs_Arcade.png",
    "width": 2048,
    "height": 1471
  },
  {
    "title": "Pointing Meme (Bike)",
    "caption": "Art by Halo.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/015-point-meme-bike.webp",
    "src": "assets/images/full/gallery/015-point-meme-bike.webp",
    "downloadName": "015.point_meme_bike.png",
    "width": 2200,
    "height": 2200
  },
  {
    "title": "Peek",
    "caption": "Art by ColorBass.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/016-peek.webp",
    "src": "assets/images/full/gallery/016-peek.webp",
    "downloadName": "016.peek.PNG",
    "width": 1825,
    "height": 1450
  },
  {
    "title": "Commission Gift",
    "caption": "Commissioned by Tracker.",
    "category": "Gallery",
    "thumb": "assets/images/thumbs/gallery/017-yonk-gift.webp",
    "src": "assets/images/full/gallery/017-yonk-gift.webp",
    "downloadName": "017.yonk_gift.png",
    "width": 1000,
    "height": 1000
  }
];
